name = "ProductPartitionModels"
uuid = "dc94b787-0653-43d5-ba3f-631bd51a31aa"
authors = ["Matt Heiner <heiner@stat.byu.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
