---
title: "Comparisons simulated interaction effect size for 3D sim"
date: today
format:
  html:
    embed-resources: true
    code-fold: true
    toc: true
    toc-location: left
execute: 
  cache: false
  warning: false
  error: false
---




```{r}
library(tidyverse)
library(patchwork)
library(kableExtra)

df <- data.frame("file" = c(
    "c8_inter1.0_common1.0_xd0.0_v0.1_dim3_prec0.01alph2.0bet1.0.csv",
    "c8_inter1.0_common2.0_xd0.0_v0.1_dim3_prec0.01alph2.0bet1.0.csv",
    "c8_inter2.0_common1.0_xd0.0_v0.1_dim3_prec0.01alph2.0bet1.0.csv"
)) %>%
    # map read these csvs into nested dataframe
    mutate(data = map(file, read_csv, )) %>%
    # unnest them
    unnest(data)
# group by file


temp <- df %>%
    reframe(
        # type 2 error
        mixT2 = mean(zeroInDPM, na.rm = T),
        kT2 = mean(zeroInk, na.rm = T),
        slrT2 = mean(zeroInSLR, na.rm = T),

        # coverage
        mixCov = mean(commonInDPM, na.rm = T),
        kCov = mean(commonInk, na.rm = T),
        slrCov = mean(commonInSLR, na.rm = T),

        # bias
        biasMix = mean(common - meanBeta1, na.rm = T),
        biasK = mean(common - meanBetakclust1, na.rm = T),
        biasSLR = mean(common - meanBetaSLR, na.rm = T),

        # MSE
        mseMix = sqrt(mean((common - meanBeta1)^2, na.rm = T)),
        mseK = sqrt(mean((common - meanBetakclust1)^2, na.rm = T)),
        mseSLR = sqrt(mean((common - meanBetaSLR)^2, na.rm = T)),
        .by = c(common, interEffect)
    )
```


# Common Effect
- Go with alpha = 2, beta= 1, prec = 0.01
```{r}
df %>%
    pivot_longer(c(
        meanBeta1, meanBetakclust1, meanBetaSLR
    )) %>%
    select(name, value, common, interEffect) %>%
    drop_na() %>%
    mutate(
        name = case_when(
            name == "meanBeta1" ~ "ppmx-common",
            name == "meanBetakclust1" ~ "kmean",
            name == "meanBetaSLR" ~ "SLR"
        )
    ) %>%
    ggplot(aes(x = value, fill = name)) +
    geom_density(alpha = 0.2) +
    facet_grid(
        rows = vars(interEffect), cols = vars(common), scales = "free",
        labeller = labeller(.rows = label_both, .cols = label_both)
    ) +
    ggtitle("Common Effect")
```

## RMSE of Common effect
```{r}
temp %>%
    select(Common = common, interEffect, `ppmx-common` = mseMix, kmean = mseK, Regression = mseSLR) %>%
    kable() %>%
    kable_paper()
```

## bias of common effect
```{r}
temp %>%
    select(Common = common, interEffect, `ppmx-common` = biasMix, kmean = biasK, Regression = biasSLR) %>%
    kable() %>%
    kable_paper()
```


## T2 error
```{r}
temp %>%
    select(Common = common, interEffect, `ppmx-common` = mixT2, kmean = kT2, Regression = slrT2) %>%
    kable() %>%
    kable_paper()
```

## Cov
```{r}
temp %>%
    select(Common = common, interEffect, `ppmx-common` = mixCov, kmean = kCov, Regression = slrCov) %>%
    kable() %>%
    kable_paper()
```


# clustering
```{r}
df %>%
    pivot_longer(c(
        rind_Mix, rind_K, rind_DPM
    )) %>%
    select(name, value, common, interEffect) %>%
    drop_na() %>%
    ggplot(aes(x = value, fill = name)) +
    geom_density(alpha = 0.2) +
    facet_grid(
        rows = vars(interEffect), cols = vars(common), scales = "free",
        labeller = labeller(.rows = label_both, .cols = label_both)
    )

df %>% 
    reframe(
        across(c(rind_Mix, rind_K, rind_DPM), function(x) median(x, na.rm = T)),
        .by = c(common, interEffect)
    ) %>%
    kable() %>%
    kable_paper()
df %>% 
    reframe(
        across(c(ncMix, ncDPM, ncK), function(x) median(x, na.rm = T)),
        .by = c(common, interEffect)
    ) %>%
    select(Common = common, interEffect, `ppmx-common` = ncMix, kmean = ncK, ppmx = ncDPM) %>%
    kable() %>%
    kable_paper()

```

# Prediction
```{r}
df %>%
    pivot_longer(c(
        midMix, kmean_MSE, midDPM, slrRMSE
    )) %>%
    select(name, value, common, interEffect) %>%
    mutate(
        name = case_when(
            name == "midMix" ~ "ppmx-common",
            name == "kmean_MSE" ~ "kmean",
            name == "midDPM" ~ "ppmx",
            name == "slrRMSE" ~ "SLR"
        )
    ) %>%
    drop_na() %>%
    ggplot(aes(x = value, fill = name)) +
    geom_density(alpha = 0.2) +
    facet_grid(
        rows = vars(interEffect), cols = vars(common), scales = "free",
        labeller = labeller(.rows = label_both, .cols = label_both)
    ) +
    ggtitle("RMSE")


df %>%
    pivot_longer(c(
        bayesPmix, bayesPDPM, #bayesPmixoos, bayesPDPMoos
    )) %>%
    select(name, value, common, interEffect) %>%
    drop_na() %>%
    mutate(
        name = case_when(
            name == "bayesPmix" ~ "ppmx-common",
            name == "bayesPDPM" ~ "ppmx",
            name == "bayesPmixoos" ~ "SLR",
            name == "meanBetaSLR" ~ "SLR"
        )
    ) %>%
    ggplot(aes(x = value, fill = name)) +
    geom_density(alpha = 0.2) +
    facet_grid(
        rows = vars(interEffect), cols = vars(common), scales = "free",
        labeller = labeller(.rows = label_both, .cols = label_both)
    ) +
    ggtitle("Bayes pvalue")

```



